name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
            cd pukiwiki-plugins/plugins/switch
            npm ci

      - name: Build
        run: |
            cd pukiwiki-plugins/plugins/switch
            npm run build

      - name: Zip dist/
        run: |
          cd pukiwiki-plugins/plugins/switch/dist
          zip -r ../../../plugin.zip .
          cd ../../../

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: plugin.zip
          generate_release_notes: true
